# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details_frame.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_details_panel(object):
    def setupUi(self, details_panel):
        details_panel.setObjectName("details_panel")
        details_panel.resize(352, 958)
        details_panel.setMaximumSize(QtCore.QSize(352, 16777215))
        details_panel.setFrameShape(QtWidgets.QFrame.Box)
        self.formLayout = QtWidgets.QFormLayout(details_panel)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.side_header_2 = QtWidgets.QLabel(details_panel)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(24)
        self.side_header_2.setFont(font)
        self.side_header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.side_header_2.setObjectName("side_header_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.side_header_2)
        self.frame_10 = QtWidgets.QFrame(details_panel)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cover_img = QtWidgets.QLabel(self.frame_10)
        self.cover_img.setMinimumSize(QtCore.QSize(280, 400))
        self.cover_img.setMaximumSize(QtCore.QSize(280, 400))
        self.cover_img.setText("")
        self.cover_img.setPixmap(QtGui.QPixmap("../test_library/Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen/002.jpg"))
        self.cover_img.setScaledContents(True)
        self.cover_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cover_img.setObjectName("cover_img")
        self.gridLayout_2.addWidget(self.cover_img, 0, 0, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.frame_10)
        self.label_12 = QtWidgets.QLabel(details_panel)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.title_text = QtWidgets.QLineEdit(details_panel)
        self.title_text.setObjectName("title_text")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.title_text)
        self.label_8 = QtWidgets.QLabel(details_panel)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.frame_7 = QtWidgets.QFrame(details_panel)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.artist_text = QtWidgets.QLineEdit(self.frame_7)
        self.artist_text.setObjectName("artist_text")
        self.verticalLayout_8.addWidget(self.artist_text)
        self.artist_dropdown = QtWidgets.QComboBox(self.frame_7)
        self.artist_dropdown.setObjectName("artist_dropdown")
        self.verticalLayout_8.addWidget(self.artist_dropdown)
        self.artist_list = QtWidgets.QListWidget(self.frame_7)
        self.artist_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.artist_list.setObjectName("artist_list")
        self.verticalLayout_8.addWidget(self.artist_list)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_7)
        self.label_11 = QtWidgets.QLabel(details_panel)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.frame_12 = QtWidgets.QFrame(details_panel)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.series_text = QtWidgets.QLineEdit(self.frame_12)
        self.series_text.setObjectName("series_text")
        self.verticalLayout_11.addWidget(self.series_text)
        self.series_dropdown = QtWidgets.QComboBox(self.frame_12)
        self.series_dropdown.setObjectName("series_dropdown")
        self.verticalLayout_11.addWidget(self.series_dropdown)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_12)
        self.label_9 = QtWidgets.QLabel(details_panel)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.order_number = QtWidgets.QSpinBox(details_panel)
        self.order_number.setMinimum(1)
        self.order_number.setObjectName("order_number")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.order_number)
        self.label_13 = QtWidgets.QLabel(details_panel)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.rating_number = QtWidgets.QSpinBox(details_panel)
        self.rating_number.setMaximum(10)
        self.rating_number.setObjectName("rating_number")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rating_number)
        self.label_10 = QtWidgets.QLabel(details_panel)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.frame_11 = QtWidgets.QFrame(details_panel)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.genre_text = QtWidgets.QLineEdit(self.frame_11)
        self.genre_text.setObjectName("genre_text")
        self.verticalLayout_10.addWidget(self.genre_text)
        self.genre_dropdown = QtWidgets.QComboBox(self.frame_11)
        self.genre_dropdown.setObjectName("genre_dropdown")
        self.verticalLayout_10.addWidget(self.genre_dropdown)
        self.genre_list = QtWidgets.QListWidget(self.frame_11)
        self.genre_list.setMaximumSize(QtCore.QSize(16777215, 75))
        self.genre_list.setObjectName("genre_list")
        self.verticalLayout_10.addWidget(self.genre_list)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.frame_11)
        self.label_14 = QtWidgets.QLabel(details_panel)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.frame_8 = QtWidgets.QFrame(details_panel)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tags_text = QtWidgets.QLineEdit(self.frame_8)
        self.tags_text.setObjectName("tags_text")
        self.verticalLayout_9.addWidget(self.tags_text)
        self.tags_dropdown = QtWidgets.QComboBox(self.frame_8)
        self.tags_dropdown.setObjectName("tags_dropdown")
        self.verticalLayout_9.addWidget(self.tags_dropdown)
        self.tags_list = QtWidgets.QListWidget(self.frame_8)
        self.tags_list.setMaximumSize(QtCore.QSize(16777215, 75))
        self.tags_list.setObjectName("tags_list")
        self.verticalLayout_9.addWidget(self.tags_list)
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.frame_8)
        self.submit_button = QtWidgets.QPushButton(details_panel)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.submit_button)

        self.retranslateUi(details_panel)
        QtCore.QMetaObject.connectSlotsByName(details_panel)

    def retranslateUi(self, details_panel):
        _translate = QtCore.QCoreApplication.translate
        details_panel.setWindowTitle(_translate("details_panel", "Frame"))
        self.side_header_2.setText(_translate("details_panel", "Book Details"))
        self.label_12.setText(_translate("details_panel", "Title"))
        self.label_8.setText(_translate("details_panel", "Artist"))
        self.label_11.setText(_translate("details_panel", "Series"))
        self.label_9.setText(_translate("details_panel", "Order"))
        self.label_13.setText(_translate("details_panel", "Rating"))
        self.label_10.setText(_translate("details_panel", "Genre"))
        self.label_14.setText(_translate("details_panel", "Tags"))
        self.submit_button.setText(_translate("details_panel", "Submit Changes"))
