# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details_frame.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_details_panel(object):
    def setupUi(self, details_panel):
        details_panel.setObjectName("details_panel")
        details_panel.resize(352, 958)
        details_panel.setMaximumSize(QtCore.QSize(352, 16777215))
        details_panel.setFrameShape(QtWidgets.QFrame.Box)
        self.formLayout = QtWidgets.QFormLayout(details_panel)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.side_header_2 = QtWidgets.QLabel(details_panel)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(24)
        self.side_header_2.setFont(font)
        self.side_header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.side_header_2.setObjectName("side_header_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.side_header_2)
        self.frame_10 = QtWidgets.QFrame(details_panel)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cover_img = QtWidgets.QLabel(self.frame_10)
        self.cover_img.setMinimumSize(QtCore.QSize(140, 200))
        self.cover_img.setMaximumSize(QtCore.QSize(140, 200))
        self.cover_img.setText("")
        self.cover_img.setPixmap(QtGui.QPixmap("../test_library/Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen/002.jpg"))
        self.cover_img.setScaledContents(True)
        self.cover_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cover_img.setObjectName("cover_img")
        self.gridLayout_2.addWidget(self.cover_img, 0, 0, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.frame_10)
        self.label_12 = QtWidgets.QLabel(details_panel)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.title_text = QtWidgets.QLineEdit(details_panel)
        self.title_text.setObjectName("title_text")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.title_text)
        self.label_8 = QtWidgets.QLabel(details_panel)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.frame_7 = QtWidgets.QFrame(details_panel)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_7)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.artists_yes_text = QtWidgets.QLineEdit(self.frame_3)
        self.artists_yes_text.setObjectName("artists_yes_text")
        self.verticalLayout_3.addWidget(self.artists_yes_text)
        self.artists_yes_list = QtWidgets.QListWidget(self.frame_3)
        self.artists_yes_list.setMinimumSize(QtCore.QSize(0, 100))
        self.artists_yes_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.artists_yes_list.setObjectName("artists_yes_list")
        self.verticalLayout_3.addWidget(self.artists_yes_list)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.artists_no_text = QtWidgets.QLineEdit(self.frame_4)
        self.artists_no_text.setObjectName("artists_no_text")
        self.verticalLayout_4.addWidget(self.artists_no_text)
        self.artists_no_list = QtWidgets.QListWidget(self.frame_4)
        self.artists_no_list.setMinimumSize(QtCore.QSize(0, 100))
        self.artists_no_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.artists_no_list.setObjectName("artists_no_list")
        self.verticalLayout_4.addWidget(self.artists_no_list)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_7)
        self.label_11 = QtWidgets.QLabel(details_panel)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.series_dropdown = QtWidgets.QComboBox(details_panel)
        self.series_dropdown.setObjectName("series_dropdown")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.series_dropdown)
        self.label_9 = QtWidgets.QLabel(details_panel)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.order_number = QtWidgets.QDoubleSpinBox(details_panel)
        self.order_number.setDecimals(1)
        self.order_number.setObjectName("order_number")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.order_number)
        self.label_13 = QtWidgets.QLabel(details_panel)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.rating_number = QtWidgets.QSpinBox(details_panel)
        self.rating_number.setMaximum(10)
        self.rating_number.setObjectName("rating_number")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.rating_number)
        self.label_2 = QtWidgets.QLabel(details_panel)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pages_text = QtWidgets.QLineEdit(details_panel)
        self.pages_text.setReadOnly(True)
        self.pages_text.setObjectName("pages_text")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pages_text)
        self.label_3 = QtWidgets.QLabel(details_panel)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.date_text = QtWidgets.QLineEdit(details_panel)
        self.date_text.setReadOnly(True)
        self.date_text.setObjectName("date_text")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.date_text)
        self.label_10 = QtWidgets.QLabel(details_panel)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.frame_11 = QtWidgets.QFrame(details_panel)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_11)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.genres_yes_text = QtWidgets.QLineEdit(self.frame_2)
        self.genres_yes_text.setObjectName("genres_yes_text")
        self.verticalLayout_2.addWidget(self.genres_yes_text)
        self.genres_yes_list = QtWidgets.QListWidget(self.frame_2)
        self.genres_yes_list.setMinimumSize(QtCore.QSize(0, 100))
        self.genres_yes_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.genres_yes_list.setObjectName("genres_yes_list")
        self.verticalLayout_2.addWidget(self.genres_yes_list)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_11)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.genres_no_text = QtWidgets.QLineEdit(self.frame)
        self.genres_no_text.setObjectName("genres_no_text")
        self.verticalLayout.addWidget(self.genres_no_text)
        self.genres_no_list = QtWidgets.QListWidget(self.frame)
        self.genres_no_list.setMinimumSize(QtCore.QSize(0, 100))
        self.genres_no_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.genres_no_list.setObjectName("genres_no_list")
        self.verticalLayout.addWidget(self.genres_no_list)
        self.horizontalLayout.addWidget(self.frame)
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.frame_11)
        self.label_14 = QtWidgets.QLabel(details_panel)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.frame_8 = QtWidgets.QFrame(details_panel)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.tags_yes_text = QtWidgets.QLineEdit(self.frame_6)
        self.tags_yes_text.setObjectName("tags_yes_text")
        self.verticalLayout_6.addWidget(self.tags_yes_text)
        self.tags_yes_list = QtWidgets.QListWidget(self.frame_6)
        self.tags_yes_list.setMinimumSize(QtCore.QSize(0, 100))
        self.tags_yes_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tags_yes_list.setObjectName("tags_yes_list")
        self.verticalLayout_6.addWidget(self.tags_yes_list)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.tags_no_text = QtWidgets.QLineEdit(self.frame_5)
        self.tags_no_text.setObjectName("tags_no_text")
        self.verticalLayout_5.addWidget(self.tags_no_text)
        self.tags_no_list = QtWidgets.QListWidget(self.frame_5)
        self.tags_no_list.setMinimumSize(QtCore.QSize(0, 100))
        self.tags_no_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tags_no_list.setObjectName("tags_no_list")
        self.verticalLayout_5.addWidget(self.tags_no_list)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.frame_8)
        self.label = QtWidgets.QLabel(details_panel)
        self.label.setObjectName("label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label)
        self.notes_text = QtWidgets.QTextEdit(details_panel)
        self.notes_text.setObjectName("notes_text")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.notes_text)
        self.submit_button = QtWidgets.QPushButton(details_panel)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.submit_button)

        self.retranslateUi(details_panel)
        QtCore.QMetaObject.connectSlotsByName(details_panel)

    def retranslateUi(self, details_panel):
        _translate = QtCore.QCoreApplication.translate
        details_panel.setWindowTitle(_translate("details_panel", "Frame"))
        self.side_header_2.setText(_translate("details_panel", "Book Details"))
        self.label_12.setText(_translate("details_panel", "Title"))
        self.label_8.setText(_translate("details_panel", "Artists"))
        self.label_6.setText(_translate("details_panel", "Applied"))
        self.label_7.setText(_translate("details_panel", "Not Applied"))
        self.artists_no_list.setSortingEnabled(True)
        self.label_11.setText(_translate("details_panel", "Series"))
        self.label_9.setText(_translate("details_panel", "Order"))
        self.label_13.setText(_translate("details_panel", "Rating"))
        self.label_2.setText(_translate("details_panel", "Pages"))
        self.label_3.setText(_translate("details_panel", "Date"))
        self.label_10.setText(_translate("details_panel", "Genres"))
        self.label_4.setText(_translate("details_panel", "Applied"))
        self.genres_yes_list.setSortingEnabled(True)
        self.label_5.setText(_translate("details_panel", "Not Applied"))
        self.genres_no_list.setSortingEnabled(True)
        self.label_14.setText(_translate("details_panel", "Tags"))
        self.label_16.setText(_translate("details_panel", "Applied"))
        self.tags_yes_list.setSortingEnabled(True)
        self.label_15.setText(_translate("details_panel", "Not Applied"))
        self.tags_no_list.setSortingEnabled(True)
        self.label.setText(_translate("details_panel", "Notes"))
        self.submit_button.setText(_translate("details_panel", "Submit Changes"))
