# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1095, 1015)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 185, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 75, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 185, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 75, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 75, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 75, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.search_bar = QtWidgets.QLineEdit(self.frame)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout_2.addWidget(self.search_bar)
        self.search_button = QtWidgets.QPushButton(self.frame)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.adv_search_button = QtWidgets.QPushButton(self.frame)
        self.adv_search_button.setObjectName("adv_search_button")
        self.horizontalLayout_2.addWidget(self.adv_search_button)
        self.sort_by = QtWidgets.QComboBox(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.sort_by.setPalette(palette)
        self.sort_by.setObjectName("sort_by")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.sort_by.addItem("")
        self.horizontalLayout_2.addWidget(self.sort_by)
        self.random_button = QtWidgets.QPushButton(self.frame)
        self.random_button.setObjectName("random_button")
        self.horizontalLayout_2.addWidget(self.random_button)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bookshelf_area = QtWidgets.QScrollArea(self.frame_2)
        self.bookshelf_area.setMaximumSize(QtCore.QSize(1542, 16777215))
        self.bookshelf_area.setFrameShape(QtWidgets.QFrame.Box)
        self.bookshelf_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bookshelf_area.setWidgetResizable(True)
        self.bookshelf_area.setObjectName("bookshelf_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 715, 937))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.bookshelf = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.bookshelf.setObjectName("bookshelf")
        self.bookshelf_area.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.bookshelf_area)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setMaximumSize(QtCore.QSize(352, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.frame_8.setPalette(palette)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_8)
        self.formLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.side_header = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(24)
        self.side_header.setFont(font)
        self.side_header.setAlignment(QtCore.Qt.AlignCenter)
        self.side_header.setObjectName("side_header")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.side_header)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.side_img = QtWidgets.QLabel(self.frame_9)
        self.side_img.setMinimumSize(QtCore.QSize(280, 400))
        self.side_img.setMaximumSize(QtCore.QSize(280, 400))
        self.side_img.setText("")
        self.side_img.setPixmap(QtGui.QPixmap("ui\\../test_library/Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen/002.jpg"))
        self.side_img.setScaledContents(True)
        self.side_img.setAlignment(QtCore.Qt.AlignCenter)
        self.side_img.setObjectName("side_img")
        self.gridLayout.addWidget(self.side_img, 0, 0, 1, 1)
        self.side_help = QtWidgets.QTextBrowser(self.frame_9)
        self.side_help.setMaximumSize(QtCore.QSize(16777215, 400))
        self.side_help.setObjectName("side_help")
        self.gridLayout.addWidget(self.side_help, 0, 1, 1, 1)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.frame_9)
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.side_title_text = QtWidgets.QLineEdit(self.frame_8)
        self.side_title_text.setObjectName("side_title_text")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.side_title_text)
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.side_artist_text = QtWidgets.QLineEdit(self.frame_5)
        self.side_artist_text.setObjectName("side_artist_text")
        self.verticalLayout_4.addWidget(self.side_artist_text)
        self.side_artist_dropdown = QtWidgets.QComboBox(self.frame_5)
        self.side_artist_dropdown.setObjectName("side_artist_dropdown")
        self.verticalLayout_4.addWidget(self.side_artist_dropdown)
        self.side_artist_list = QtWidgets.QListWidget(self.frame_5)
        self.side_artist_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.side_artist_list.setObjectName("side_artist_list")
        self.verticalLayout_4.addWidget(self.side_artist_list)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_5)
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.side_collection_text = QtWidgets.QLineEdit(self.frame_6)
        self.side_collection_text.setObjectName("side_collection_text")
        self.verticalLayout_5.addWidget(self.side_collection_text)
        self.side_collection_dropdown = QtWidgets.QComboBox(self.frame_6)
        self.side_collection_dropdown.setObjectName("side_collection_dropdown")
        self.verticalLayout_5.addWidget(self.side_collection_dropdown)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.frame_6)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.side_order_number = QtWidgets.QSpinBox(self.frame_8)
        self.side_order_number.setObjectName("side_order_number")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.side_order_number)
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.side_rating_number = QtWidgets.QSpinBox(self.frame_7)
        self.side_rating_number.setMaximum(10)
        self.side_rating_number.setObjectName("side_rating_number")
        self.horizontalLayout_3.addWidget(self.side_rating_number)
        self.side_rating_toggle = QtWidgets.QCheckBox(self.frame_7)
        self.side_rating_toggle.setObjectName("side_rating_toggle")
        self.horizontalLayout_3.addWidget(self.side_rating_toggle)
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.frame_7)
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.frame_3 = QtWidgets.QFrame(self.frame_8)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.side_genre_text = QtWidgets.QLineEdit(self.frame_3)
        self.side_genre_text.setObjectName("side_genre_text")
        self.verticalLayout_2.addWidget(self.side_genre_text)
        self.side_genre_dropdown = QtWidgets.QComboBox(self.frame_3)
        self.side_genre_dropdown.setObjectName("side_genre_dropdown")
        self.verticalLayout_2.addWidget(self.side_genre_dropdown)
        self.side_genre_list = QtWidgets.QListWidget(self.frame_3)
        self.side_genre_list.setMaximumSize(QtCore.QSize(16777215, 75))
        self.side_genre_list.setObjectName("side_genre_list")
        self.verticalLayout_2.addWidget(self.side_genre_list)
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.frame_3)
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.frame_4 = QtWidgets.QFrame(self.frame_8)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.side_tags_text = QtWidgets.QLineEdit(self.frame_4)
        self.side_tags_text.setObjectName("side_tags_text")
        self.verticalLayout_3.addWidget(self.side_tags_text)
        self.side_tags_dropdown = QtWidgets.QComboBox(self.frame_4)
        self.side_tags_dropdown.setObjectName("side_tags_dropdown")
        self.verticalLayout_3.addWidget(self.side_tags_dropdown)
        self.side_tags_list = QtWidgets.QListWidget(self.frame_4)
        self.side_tags_list.setMaximumSize(QtCore.QSize(16777215, 75))
        self.side_tags_list.setObjectName("side_tags_list")
        self.verticalLayout_3.addWidget(self.side_tags_list)
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.frame_4)
        self.side_submit_button = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.side_submit_button.setFont(font)
        self.side_submit_button.setObjectName("side_submit_button")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.side_submit_button)
        self.horizontalLayout.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manga Viewer"))
        self.label_8.setText(_translate("MainWindow", "Search"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.adv_search_button.setText(_translate("MainWindow", "Advanced Search"))
        self.sort_by.setItemText(0, _translate("MainWindow", "Alphabetically"))
        self.sort_by.setItemText(1, _translate("MainWindow", "Rating"))
        self.sort_by.setItemText(2, _translate("MainWindow", "Pages"))
        self.sort_by.setItemText(3, _translate("MainWindow", "Randomly"))
        self.random_button.setText(_translate("MainWindow", "Random"))
        self.side_header.setText(_translate("MainWindow", "Details"))
        self.side_help.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">Type  Color     Prefix</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">AND</span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#00ff00;\">   Green     </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">+</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">NOT   </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#ff0000;\">Red       </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">-</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">OR    </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#00ffff;\">Blue      </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">/</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">If no prefix is added, the filter will default to </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#00ff00;\">AND</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\'; font-size:12pt; color:#00ff00;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">A rating and order of 0 is all inclusive</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Title"))
        self.label_2.setText(_translate("MainWindow", "Artist"))
        self.label_3.setText(_translate("MainWindow", "Collection"))
        self.label_4.setText(_translate("MainWindow", "Order"))
        self.label_5.setText(_translate("MainWindow", "Rating"))
        self.side_rating_toggle.setText(_translate("MainWindow", "include higher ratings?"))
        self.label_6.setText(_translate("MainWindow", "Genre"))
        self.label_7.setText(_translate("MainWindow", "Tags"))
        self.side_submit_button.setText(_translate("MainWindow", "Submit Changes"))
