# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_frame.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_panel(object):
    def setupUi(self, search_panel):
        search_panel.setObjectName("search_panel")
        search_panel.resize(352, 958)
        search_panel.setMaximumSize(QtCore.QSize(352, 16777215))
        search_panel.setFrameShape(QtWidgets.QFrame.Box)
        self.formLayout = QtWidgets.QFormLayout(search_panel)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(search_panel)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(24)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(search_panel)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.title_text = QtWidgets.QLineEdit(search_panel)
        self.title_text.setObjectName("title_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.title_text)
        self.label_16 = QtWidgets.QLabel(search_panel)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.frame_19 = QtWidgets.QFrame(search_panel)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.artists_text = QtWidgets.QLineEdit(self.frame_19)
        self.artists_text.setObjectName("artists_text")
        self.verticalLayout_11.addWidget(self.artists_text)
        self.artists_dropdown = QtWidgets.QComboBox(self.frame_19)
        self.artists_dropdown.setObjectName("artists_dropdown")
        self.verticalLayout_11.addWidget(self.artists_dropdown)
        self.artists_list = QtWidgets.QListWidget(self.frame_19)
        self.artists_list.setObjectName("artists_list")
        self.verticalLayout_11.addWidget(self.artists_list)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_19)
        self.label_17 = QtWidgets.QLabel(search_panel)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.frame_10 = QtWidgets.QFrame(search_panel)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.series_text = QtWidgets.QLineEdit(self.frame_10)
        self.series_text.setObjectName("series_text")
        self.verticalLayout_10.addWidget(self.series_text)
        self.series_dropdown = QtWidgets.QComboBox(self.frame_10)
        self.series_dropdown.setObjectName("series_dropdown")
        self.verticalLayout_10.addWidget(self.series_dropdown)
        self.series_list = QtWidgets.QListWidget(self.frame_10)
        self.series_list.setObjectName("series_list")
        self.verticalLayout_10.addWidget(self.series_list)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.frame_10)
        self.label_18 = QtWidgets.QLabel(search_panel)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.order_number = QtWidgets.QSpinBox(search_panel)
        self.order_number.setObjectName("order_number")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.order_number)
        self.label_19 = QtWidgets.QLabel(search_panel)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.frame_7 = QtWidgets.QFrame(search_panel)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rating_number = QtWidgets.QSpinBox(self.frame_7)
        self.rating_number.setMaximum(10)
        self.rating_number.setObjectName("rating_number")
        self.horizontalLayout_3.addWidget(self.rating_number)
        self.rating_toggle = QtWidgets.QCheckBox(self.frame_7)
        self.rating_toggle.setObjectName("rating_toggle")
        self.horizontalLayout_3.addWidget(self.rating_toggle)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.frame_7)
        self.label_20 = QtWidgets.QLabel(search_panel)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.frame_20 = QtWidgets.QFrame(search_panel)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.genres_text = QtWidgets.QLineEdit(self.frame_20)
        self.genres_text.setObjectName("genres_text")
        self.verticalLayout_12.addWidget(self.genres_text)
        self.genres_dropdown = QtWidgets.QComboBox(self.frame_20)
        self.genres_dropdown.setObjectName("genres_dropdown")
        self.verticalLayout_12.addWidget(self.genres_dropdown)
        self.genres_list = QtWidgets.QListWidget(self.frame_20)
        self.genres_list.setObjectName("genres_list")
        self.verticalLayout_12.addWidget(self.genres_list)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.frame_20)
        self.label_21 = QtWidgets.QLabel(search_panel)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.frame_21 = QtWidgets.QFrame(search_panel)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tags_text = QtWidgets.QLineEdit(self.frame_21)
        self.tags_text.setObjectName("tags_text")
        self.verticalLayout_13.addWidget(self.tags_text)
        self.tags_dropdown = QtWidgets.QComboBox(self.frame_21)
        self.tags_dropdown.setObjectName("tags_dropdown")
        self.verticalLayout_13.addWidget(self.tags_dropdown)
        self.tags_list = QtWidgets.QListWidget(self.frame_21)
        self.tags_list.setObjectName("tags_list")
        self.verticalLayout_13.addWidget(self.tags_list)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.frame_21)
        self.side_help = QtWidgets.QTextBrowser(search_panel)
        self.side_help.setMaximumSize(QtCore.QSize(16777215, 400))
        self.side_help.setObjectName("side_help")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.side_help)
        self.submit_button = QtWidgets.QPushButton(search_panel)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.submit_button)

        self.retranslateUi(search_panel)
        QtCore.QMetaObject.connectSlotsByName(search_panel)

    def retranslateUi(self, search_panel):
        _translate = QtCore.QCoreApplication.translate
        search_panel.setWindowTitle(_translate("search_panel", "Frame"))
        self.label_14.setText(_translate("search_panel", "Advanced Search"))
        self.label_15.setText(_translate("search_panel", "Title"))
        self.label_16.setText(_translate("search_panel", "Artists"))
        self.label_17.setText(_translate("search_panel", "Series"))
        self.label_18.setText(_translate("search_panel", "Order"))
        self.label_19.setText(_translate("search_panel", "Rating"))
        self.rating_toggle.setText(_translate("search_panel", "include higher ratings?"))
        self.label_20.setText(_translate("search_panel", "Genres"))
        self.label_21.setText(_translate("search_panel", "Tags"))
        self.side_help.setHtml(_translate("search_panel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">Type  Color     Prefix</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">AND</span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#00ff00;\">   Green     </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">+</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">NOT   </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#ff0000;\">Red       </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">-</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">OR    </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#00ffff;\">Blue      </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">/</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\'; font-size:12pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">If no prefix is added, the filter will default to </span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#00ff00;\">AND</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\'; font-size:12pt; color:#00ff00;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">An order of 0 is all inclusive</span></p></body></html>"))
        self.submit_button.setText(_translate("search_panel", "Filter"))
